--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend.lua"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")
Node:setLocalZOrder(0)

--Create Button_2
local Button_2 = ccui.Button:create()
Button_2:ignoreContentAdaptWithSize(false)
Button_2:loadTextureNormal("Default/Button_Normal.png",0)
Button_2:loadTexturePressed("Default/Button_Press.png",0)
Button_2:loadTextureDisabled("Default/Button_Disable.png",0)
Button_2:setTitleFontSize(14)
Button_2:setTitleText("Button")
Button_2:setTitleColor(cc.c3b(65, 65, 70))
Button_2:setFlippedX(false)
Button_2:setFlippedY(false)
Button_2:setScale9Enabled(true)
Button_2:setCapInsets(cc.rect(15,11,16,14))
Button_2:setBright(true)
Button_2:setTouchEnabled(true)
Button_2:setLayoutComponentEnabled(true)
Button_2:setName("Button_2")
Button_2:setLocalZOrder(0)
Button_2:setTag(6)
Button_2:setCascadeColorEnabled(true)
Button_2:setCascadeOpacityEnabled(true)
Button_2:setVisible(true)
Button_2:setAnchorPoint(0.5, 0.5)
Button_2:setPosition(142.8, 103.1)
Button_2:setScaleX(1)
Button_2:setScaleY(1)
Button_2:setRotation(0)
Button_2:setRotationSkewX(0)
Button_2:setRotationSkewY(0)
Button_2:setOpacity(255)
Button_2:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Button_2)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(46, 36))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(119.8)
layout:setRightMargin(-165.8)
layout:setTopMargin(-121.1)
layout:setBottomMargin(85.1)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(Button_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(5)
result['animation']:setTimeSpeed(1)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setX(168)
localFrame:setY(119.5)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(true)
localFrame:setX(42)
localFrame:setY(37.5)
PositionTimeline:addFrame(localFrame)

PositionTimeline:setNode(Button_2)
result['animation']:addTimeline(PositionTimeline)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setScaleX(1)
localFrame:setScaleY(1)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(true)
localFrame:setScaleX(1)
localFrame:setScaleY(1)
ScaleTimeline:addFrame(localFrame)

ScaleTimeline:setNode(Button_2)
result['animation']:addTimeline(ScaleTimeline)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setSkewX(0)
localFrame:setSkewY(0)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(true)
localFrame:setSkewX(0)
localFrame:setSkewY(0)
RotationSkewTimeline:addFrame(localFrame)

RotationSkewTimeline:setNode(Button_2)
result['animation']:addTimeline(RotationSkewTimeline)
--Create Animation List

result['root'] = Node
return result;
end

return Result

